name: Build and deployment

on:
  pull_request:
    branches: [ "main" ]



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish Firebase Auth
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publish
        env:
          ossrhUrl: ${{ secrets.OSSH_URL }}
          ossrhUsername: ${{ secrets.OSSH_USERNAME }}
          ossrhPassword: ${{ secrets.OSSH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASS }}
